FROM node:22-alpine

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port for the Next.js development server
EXPOSE 3000

# Start the development server
CMD ["npm", "run", "dev"]