FROM node:22-alpine

# Set the working directory
WORKDIR /app
ENV NODE_ENV=development

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose the port for the Next.js development server
EXPOSE 3000

# Start the development server
CMD ["npm", "run", "dev"]