version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgweb_dev_postgres
    environment:
      POSTGRES_USER: dev_admin
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_admin_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_admin -d dev_admin_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  dex:
    image: ghcr.io/dexidp/dex:latest-distroless
    container_name: pgweb_dev_dex
    volumes:
      - ./dex_config.yml:/etc/dex/config.docker.yaml:ro
    ports:
      - "5556:5556"
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: pgweb_dev_backend
    volumes:
      - ./backend:/app
    environment:
      PG_ADMIN_DSN: "postgres://dev_admin:dev_password@postgres:5432/dev_admin_db?sslmode=disable"
      APP_DB_DSN: "postgres://dev_admin:dev_password@postgres:5432/dev_admin_db?sslmode=disable"
      GIN_MODE: "debug"
      SESSION_SECRET_KEY: "dev-session-secret"
      PGWEB_TRUSTED_HEADER: "X-Forwarded-Email"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      dex:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: pgweb_dev_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/svelte.config.js:/app/svelte.config.js
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/test-rendering.js:/app/test-rendering.js
      - ./frontend/vite.config.ts:/app/vite.config.ts
    depends_on:
      backend:
        condition: service_healthy
    #command: ls -al
    environment:
      VITE_API_BASE_URL: "http://localhost/api"

  nginx:
    image: nginx:latest
    container_name: pgweb_dev_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy