version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgweb_dev_postgres
    environment:
      POSTGRES_USER: dev_admin
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_admin_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_admin -d dev_admin_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  dex:
    image: ghcr.io/dexidp/dex:latest-distroless
    container_name: pgweb_dev_dex
    volumes:
      - ./dex_config.yml:/etc/dex/config.docker.yaml:ro
    ports:
      - "5556:5556"
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: pgweb_dev_backend
    volumes:
      - ./backend:/app
    environment:
      PG_ADMIN_DSN: "postgres://dev_admin:dev_password@postgres:5432/dev_admin_db?sslmode=disable"
      APP_DB_DSN: "postgres://dev_admin:dev_password@postgres:5432/dev_admin_db?sslmode=disable"
      GIN_MODE: "debug"
      SESSION_SECRET_KEY: "dev-session-secret"
      PGWEB_TRUSTED_HEADER: "X-Forwarded-Email"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      dex:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend # Assuming frontend code is in a 'frontend' subdirectory
      dockerfile: Dockerfile # Dockerfile for Vite/Svelte app
    container_name: pgweb_frontend
    ports:
      - "80:80"   # Host 5173 maps to Nginx container port 80
                 # The frontend Dockerfile currently uses Nginx on port 80.
                 # So this should map host 5173 to container 80 if using Nginx.
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./frontend/public:/etc/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
