issuer: http://dex:5556/dex
storage:
  type: postgres
  config:
    host: postgres
    port: 5432
    user: test_admin
    password: test_password
    database: test_admin_db
    ssl:
      mode: disable

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
- id: test-client
  secret: test-secret
  name: 'Test Client'
  redirectURIs:
  - 'http://backend:8080/auth/oidc/callback'

enablePasswordDB: true
staticPasswords:
- email: "test@example.com"
  password: "testpassword"
  hash: "$2y$10$BTkzGSyJvpf0.BAk3V6pjuv8yI9WmAWJw89kXj9wC14kMyhkv/Fca"
  username: "testuser"