FROM mcr.microsoft.com/playwright:v1.59.1-jammy

WORKDIR /e2e

RUN apt-get update && apt-get install -y dumb-init

COPY package*.json ./
RUN npm ci

COPY playwright.config.js ./
COPY tests/playwright/ ./tests/playwright/

CMD ["npx", "playwright", "test"]