root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "APP_ENV=development ./tmp/main"
delay = 1000 # ms
exclude_dir = ["tmp", "vendor", "frontend"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[run]
args = []
is_multistage = true
proxy_cmd = "dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient --log"
build_delay = 200 # ms
app_start_delay = 0 # ms
app_start_timeout = 60000 # ms
app_stop_timeout = 5000 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true