FROM golang:1.23-alpine

# Set necessary environment variables for building
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
ENV PATH="/go/bin/${GOOS}_${GOARCH}/:${PATH}"

# Set the Current Working Directory inside the container
WORKDIR /app

# Install git for go mod download if private repos are involved (good practice)
RUN apk add --no-cache git

# Install ca-certificates to trust TLS certificates from HTTPS services
RUN apk --no-cache add ca-certificates tzdata

# Copy go.mod and go.sum files to download dependencies
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# Install air for hot-reloading
RUN go install github.com/air-verse/air@v1.61.7

# Expose port 8080 to the outside world (as defined in main.go)
EXPOSE 8080

# Command to run the executable with air for hot-reloading
# The actual .env file or environment variables should be provided at runtime.
CMD ["air", "-c", ".air.toml"]