# Use the official Golang image as a base image
FROM golang:1.23-alpine

# Set the current working directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod ./
COPY go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the test binary (optional, but good for pre-compilation)
# RUN go test -c -o /usr/local/bin/dbutils.test ./dbutils

# Entrypoint for running tests
CMD ["go", "test", "./..."]
