name: Run Tests

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set image names for main branch push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "BACKEND_IMAGE=ghcr.io/${{ github.repository_owner }}/pgweb-backend:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE=ghcr.io/${{ github.repository_owner }}/pgweb-frontend:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Pull images for main branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker pull ${{ env.BACKEND_IMAGE }}
          docker pull ${{ env.FRONTEND_IMAGE }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Run tests
        env:
          BACKEND_IMAGE: ${{ env.BACKEND_IMAGE }}
          FRONTEND_IMAGE: ${{ env.FRONTEND_IMAGE }}
        run: docker-compose -f compose.test.yml up --exit-code-from cypress
